using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using UnityEngine;
using Unity.Netcode;
using Unity.Netcode.Transports.UTP;
using Unity.Networking.Transport.Relay;
using Unity.Services.Core;
using Unity.Services.Relay;
using Unity.Services.Relay.Models;
using Unity.Services.Authentication;

namespace KawaiiCoolIsland.Multiplayer
{
    /// <summary>
    /// Central network manager singleton for KawaiiCool Island.
    /// Wraps Unity Netcode for GameObjects (<see cref="NetworkManager.Singleton"/>)
    /// and adds Relay service integration, player spawning / tracking,
    /// connection-quality gating, and room-aware lifecycle management.
    /// </summary>
    /// <remarks>
    /// This class is a <see cref="Singleton{T}"/> — it persists across scene loads
    /// and must exist in the Bootstrap scene before any network operation.
    /// </remarks>
    public class KawaiiNetworkManager : Singleton<KawaiiNetworkManager>
    {
        // ================================================================
        // Inspector
        // ================================================================

        [Header("Prefabs")]
        [Tooltip("Player avatar prefab containing NetworkObject + NetworkedPlayer.")]
        public GameObject PlayerPrefab;

        [Header("Settings")]
        [Tooltip("Default maximum concurrent players per session.")]
        public int MaxPlayers = 20;

        [Tooltip("Proximity text-chat radius in world units.")]
        public float ProximityChatRange = NetworkConstants.CHAT_RANGE_DEFAULT;

        [Tooltip("Network tick rate in Hz. Must match NGO Project Settings.")]
        public float PositionSyncRate = NetworkConstants.POSITION_SYNC_INTERVAL;

        [Tooltip("If true, routes connections through Unity Relay for NAT traversal.")]
        public bool UseRelay = true;

        [Header("Transport")]
        [Tooltip("Reference to the Unity Transport component on the same GameObject.")]
        public UnityTransport Transport;

        // ================================================================
        // Private state
        // ================================================================

        /// <summary>
        /// Active player lookups keyed by <see cref="NetworkObjectId"/>.
        /// Only populated while connected.
        /// </summary>
        private readonly Dictionary<ulong, NetworkedPlayer> _connectedPlayers = new();

        /// <summary>
        /// The join code generated by Relay. Share this with friends for manual entry.
        /// </summary>
        private string _currentJoinCode;

        /// <summary>
        /// Whether this instance is currently acting as the network host.
        /// </summary>
        private bool _isHost;

        /// <summary>
        /// Whether Relay initialisation is in progress (prevents double-start).
        /// </summary>
        private bool _isInitializingRelay;

        /// <summary>
        /// Cached Relay allocation for host reconnection scenarios.
        /// </summary>
        private Allocation _relayAllocation;

        /// <summary>
        /// Cached Relay join allocation for client connections.
        /// </summary>
        private JoinAllocation _relayJoinAllocation;

        // ================================================================
        // Properties
        // ================================================================

        /// <summary>
        /// Whether the local client is connected to a host or is itself the host.
        /// </summary>
        public bool IsConnected => NetworkManager.Singleton != null &&
            (NetworkManager.Singleton.IsConnectedClient || IsHost);

        /// <summary>
        /// Whether this instance is the network host (server + client).
        /// </summary>
        public bool IsHost => _isHost;

        /// <summary>
        /// Number of currently connected players (including the local player).
        /// </summary>
        public int ConnectedPlayerCount => _connectedPlayers.Count;

        /// <summary>
        /// The current room / session identifier (join code or GUID).
        /// </summary>
        public string CurrentRoomId { get; private set; }

        /// <summary>
        /// The <see cref="RoomType"/> of the currently occupied room.
        /// </summary>
        public RoomType CurrentRoomType { get; private set; }

        /// <summary>
        /// The Relay join code for the current session. Null if not using Relay.
        /// </summary>
        public string CurrentJoinCode => _currentJoinCode;

        /// <summary>
        /// Whether Relay services are signed in and ready.
        /// </summary>
        public bool IsRelayReady { get; private set; }

        // ================================================================
        // Lifecycle
        // ================================================================

        protected override void Awake()
        {
            base.Awake();
            DontDestroyOnLoad(gameObject);

            // Cache transport if not manually assigned
            if (Transport == null)
                Transport = GetComponent<UnityTransport>();

            // Validate player prefab has the required NetworkObject
            if (PlayerPrefab != null && PlayerPrefab.GetComponent<NetworkObject>() == null)
            {
                Debug.LogError(
                    $"[{nameof(KawaiiNetworkManager)}] PlayerPrefab is missing a NetworkObject component!",
                    PlayerPrefab);
            }
        }

        private void Start()
        {
            // Wire NGO callbacks
            if (NetworkManager.Singleton != null)
            {
                NetworkManager.Singleton.OnClientConnectedCallback  += OnClientConnected;
                NetworkManager.Singleton.OnClientDisconnectCallback += OnClientDisconnected;
                NetworkManager.Singleton.OnServerStarted            += OnServerStarted;
                NetworkManager.Singleton.OnTransportFailure         += OnTransportFailure;
            }
        }

        private void OnDestroy()
        {
            if (NetworkManager.Singleton != null)
            {
                NetworkManager.Singleton.OnClientConnectedCallback  -= OnClientConnected;
                NetworkManager.Singleton.OnClientDisconnectCallback -= OnClientDisconnected;
                NetworkManager.Singleton.OnServerStarted            -= OnServerStarted;
                NetworkManager.Singleton.OnTransportFailure         -= OnTransportFailure;
            }
        }

        // ================================================================
        // Connection lifecycle — Host
        // ================================================================

        /// <summary>
        /// Starts a network host with Relay allocation.
        /// </summary>
        /// <param name="maxPlayers">Maximum concurrent players.</param>
        /// <returns>The Relay join code to share with friends.</returns>
        public async Task<string> StartHost(int maxPlayers = 20)
        {
            if (_isHost)
            {
                Debug.LogWarning($"[{nameof(KawaiiNetworkManager)}] Already hosting.");
                return _currentJoinCode;
            }

            MaxPlayers = maxPlayers;

            try
            {
                // Initialise Unity Services if needed
                await EnsureServicesInitializedAsync();

                // Setup Relay
                if (UseRelay)
                {
                    string joinCode = await AllocateRelay(maxPlayers);
                    _currentJoinCode = joinCode;
                }
                else
                {
                    // Direct IP — use default port
                    Transport.SetConnectionData(
                        "0.0.0.0", (ushort)NetworkConstants.DEFAULT_PORT);
                }

                // Register prefab and start host
                if (PlayerPrefab != null)
                    NetworkManager.Singleton.NetworkConfig.PlayerPrefab = PlayerPrefab;

                bool started = NetworkManager.Singleton.StartHost();
                if (!started)
                {
                    Debug.LogError($"[{nameof(KawaiiNetworkManager)}] StartHost() returned false.");
                    return null;
                }

                _isHost = true;
                CurrentRoomId = Guid.NewGuid().ToString("N").Substring(0, 8).ToUpper();
                CurrentRoomType = RoomType.Hub;

                Debug.Log(
                    $"[{nameof(KawaiiNetworkManager)}] Host started. Join code: {_currentJoinCode ?? "N/A (Direct)"}");

                OnHostStarted?.Invoke();
                return _currentJoinCode;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[{nameof(KawaiiNetworkManager)}] StartHost failed: {ex.Message}");
                Disconnect();
                throw;
            }
        }

        // ================================================================
        // Connection lifecycle — Client
        // ================================================================

        /// <summary>
        /// Connects to a host using a Relay join code.
        /// </summary>
        /// <param name="joinCode">The join code shared by the host.</param>
        public async Task StartClient(string joinCode)
        {
            if (IsConnected)
            {
                Debug.LogWarning($"[{nameof(KawaiiNetworkManager)}] Already connected. Disconnect first.");
                return;
            }

            try
            {
                await EnsureServicesInitializedAsync();

                if (UseRelay && !string.IsNullOrEmpty(joinCode))
                {
                    await JoinRelay(joinCode);
                    _currentJoinCode = joinCode;
                }
                else
                {
                    // Direct IP connection — parse as "ip:port"
                    ParseDirectConnection(joinCode ?? $"127.0.0.1:{NetworkConstants.DEFAULT_PORT}");
                }

                bool started = NetworkManager.Singleton.StartClient();
                if (!started)
                {
                    Debug.LogError($"[{nameof(KawaiiNetworkManager)}] StartClient() returned false.");
                    return;
                }

                Debug.Log($"[{nameof(KawaiiNetworkManager)}] Client connecting with join code '{joinCode}'...");
            }
            catch (Exception ex)
            {
                Debug.LogError($"[{nameof(KawaiiNetworkManager)}] StartClient failed: {ex.Message}");
                Disconnect();
                throw;
            }
        }

        /// <summary>
        /// Disconnects from the current session and cleans up all state.
        /// </summary>
        public void Disconnect()
        {
            if (NetworkManager.Singleton != null)
            {
                if (NetworkManager.Singleton.IsHost)
                    NetworkManager.Singleton.Shutdown();
                else if (NetworkManager.Singleton.IsConnectedClient)
                    NetworkManager.Singleton.Shutdown();
            }

            // Cleanup state
            _isHost = false;
            _currentJoinCode = null;
            _relayAllocation = null;
            _relayJoinAllocation = null;
            CurrentRoomId = null;
            CurrentRoomType = RoomType.Hub;
            _connectedPlayers.Clear();

            OnDisconnected?.Invoke();
            Debug.Log($"[{nameof(KawaiiNetworkManager)}] Disconnected and state reset.");
        }

        // ================================================================
        // Relay integration
        // ================================================================

        /// <summary>
        /// Allocates a Relay server for the host.
        /// </summary>
        /// <param name="maxPlayers">Maximum connections (including host).</param>
        /// <returns>The join code to share with clients.</returns>
        public async Task<string> AllocateRelay(int maxPlayers)
        {
            try
            {
                // Ensure authenticated
                if (!AuthenticationService.Instance.IsSignedIn)
                {
                    await AuthenticationService.Instance.SignInAnonymouslyAsync();
                }

                // Create allocation
                _relayAllocation = await RelayService.Instance.CreateAllocationAsync(
                    maxPlayers,
                    region: null); // auto-select best region

                // Get join code
                _currentJoinCode = await RelayService.Instance.GetJoinCodeAsync(
                    _relayAllocation.AllocationId);

                // Configure Unity Transport with Relay data
                var relayServerData = new RelayServerData(
                    _relayAllocation,
                    NetworkConstants.RELAY_CONNECTION_TYPE);

                Transport.SetRelayServerData(relayServerData);

                IsRelayReady = true;
                Debug.Log($"[{nameof(KawaiiNetworkManager)}] Relay allocated. Join code: {_currentJoinCode}");

                return _currentJoinCode;
            }
            catch (RelayServiceException ex)
            {
                Debug.LogError($"[{nameof(KawaiiNetworkManager)}] Relay allocation failed: {ex.Message}");
                IsRelayReady = false;
                throw;
            }
        }

        /// <summary>
        /// Retrieves a fresh join code for an existing Relay allocation.
        /// Call this if the previous code expired or was lost.
        /// </summary>
        public async Task<string> GetJoinCode()
        {
            if (_relayAllocation == null)
            {
                Debug.LogWarning($"[{nameof(KawaiiNetworkManager)}] No active Relay allocation.");
                return null;
            }

            try
            {
                _currentJoinCode = await RelayService.Instance.GetJoinCodeAsync(
                    _relayAllocation.AllocationId);
                return _currentJoinCode;
            }
            catch (RelayServiceException ex)
            {
                Debug.LogError($"[{nameof(KawaiiNetworkManager)}] GetJoinCode failed: {ex.Message}");
                return null;
            }
        }

        /// <summary>
        /// Joins a Relay allocation using a join code.
        /// </summary>
        private async Task JoinRelay(string joinCode)
        {
            try
            {
                if (!AuthenticationService.Instance.IsSignedIn)
                {
                    await AuthenticationService.Instance.SignInAnonymouslyAsync();
                }

                _relayJoinAllocation = await RelayService.Instance.JoinAllocationAsync(joinCode);

                var relayServerData = new RelayServerData(
                    _relayJoinAllocation,
                    NetworkConstants.RELAY_CONNECTION_TYPE);

                Transport.SetRelayServerData(relayServerData);

                IsRelayReady = true;
                Debug.Log($"[{nameof(KawaiiNetworkManager)}] Joined Relay with code '{joinCode}'.");
            }
            catch (RelayServiceException ex)
            {
                Debug.LogError($"[{nameof(KawaiiNetworkManager)}] Relay join failed: {ex.Message}");
                IsRelayReady = false;
                throw;
            }
        }

        // ================================================================
        // Player management API
        // ================================================================

        /// <summary>
        /// Gets a <see cref="NetworkedPlayer"/> by its network object ID.
        /// </summary>
        /// <param name="clientId">The <see cref="NetworkObjectId"/> of the player.</param>
        /// <returns>The player component, or <c>null</c> if not found.</returns>
        public NetworkedPlayer GetPlayer(ulong clientId)
        {
            _connectedPlayers.TryGetValue(clientId, out var player);
            return player;
        }

        /// <summary>
        /// Gets the local player's <see cref="NetworkedPlayer"/> component.
        /// </summary>
        /// <returns>The local player, or <c>null</c> if not connected.</returns>
        public NetworkedPlayer GetLocalPlayer()
        {
            if (NetworkManager.Singleton?.LocalClient?.PlayerObject != null)
            {
                return NetworkManager.Singleton.LocalClient.PlayerObject
                    .GetComponent<NetworkedPlayer>();
            }

            // Fallback: search in our registry
            ulong localId = NetworkManager.Singleton?.LocalClientId ?? 0;
            return GetPlayer(localId);
        }

        /// <summary>
        /// Returns all currently connected players (including local).
        /// </summary>
        /// <returns>A new list copied from the internal registry.</returns>
        public List<NetworkedPlayer> GetAllPlayers()
        {
            return _connectedPlayers.Values.ToList();
        }

        /// <summary>
        /// Returns all players within <paramref name="radius"/> of <paramref name="position"/>.
        /// Used by proximity chat and spatial audio.
        /// </summary>
        public List<NetworkedPlayer> GetNearbyPlayers(Vector3 position, float radius)
        {
            float radiusSqr = radius * radius;
            return _connectedPlayers.Values
                .Where(p => (p.Position - position).sqrMagnitude <= radiusSqr)
                .ToList();
        }

        /// <summary>
        /// Returns all players currently in the specified room.
        /// </summary>
        /// <param name="roomId">Room identifier.</param>
        public List<NetworkedPlayer> GetPlayersInRoom(string roomId)
        {
            if (RoomManager.Instance?.CurrentRoomId == roomId)
            {
                return GetAllPlayers();
            }
            return new List<NetworkedPlayer>();
        }

        /// <summary>
        /// Internal: registers a spawned player in the lookup dictionary.
        /// Called by <see cref="NetworkedPlayer.OnNetworkSpawn"/>.
        /// </summary>
        internal void RegisterPlayer(NetworkedPlayer player)
        {
            if (player == null) return;
            _connectedPlayers[player.NetworkObjectId] = player;
            Debug.Log($"[{nameof(KawaiiNetworkManager)}] Registered player {player.NetworkObjectId} ({player.DisplayName}). Total: {_connectedPlayers.Count}");
        }

        /// <summary>
        /// Internal: removes a despawned player from the lookup dictionary.
        /// Called by <see cref="NetworkedPlayer.OnNetworkDespawn"/>.
        /// </summary>
        internal void UnregisterPlayer(ulong networkObjectId)
        {
            if (_connectedPlayers.Remove(networkObjectId))
            {
                Debug.Log($"[{nameof(KawaiiNetworkManager)}] Unregistered player {networkObjectId}. Total: {_connectedPlayers.Count}");
            }
        }

        // ================================================================
        // NGO callbacks
        // ================================================================

        /// <summary>
        /// Fired on the server when a new client connects.
        /// </summary>
        private void OnClientConnected(ulong clientId)
        {
            Debug.Log($"[{nameof(KawaiiNetworkManager)}] Client connected: {clientId}");

            // Spawn player object for the new client
            SpawnPlayer(clientId);

            OnPlayerConnected?.Invoke(clientId);
        }

        /// <summary>
        /// Fired on the server and all clients when a client disconnects.
        /// </summary>
        private void OnClientDisconnected(ulong clientId)
        {
            Debug.Log($"[{nameof(KawaiiNetworkManager)}] Client disconnected: {clientId}");

            DespawnPlayer(clientId);

            // Notify RoomManager
            if (RoomManager.Instance != null)
            {
                var roomInfo = RoomManager.Instance.GetPlayerInfo(clientId.ToString());
                if (roomInfo != null)
                    RoomManager.Instance.LeaveRoom();
            }

            OnPlayerDisconnected?.Invoke(clientId);

            // If we're a client and the host disconnected, clean up
            if (!IsHost && !NetworkManager.Singleton.IsConnectedClient)
            {
                Disconnect();
            }
        }

        /// <summary>
        /// Fired when the server starts listening.
        /// </summary>
        private void OnServerStarted()
        {
            Debug.Log($"[{nameof(KawaiiNetworkManager)}] Server started listening.");
        }

        /// <summary>
        /// Fired when the transport layer encounters a fatal error.
        /// </summary>
        private void OnTransportFailure()
        {
            Debug.LogError($"[{nameof(KawaiiNetworkManager)}] Transport failure! Disconnecting.");
            Disconnect();
        }

        // ================================================================
        // Spawn / Despawn
        // ================================================================

        /// <summary>
        /// Spawns a player avatar for the specified client. Server only.
        /// </summary>
        private void SpawnPlayer(ulong clientId)
        {
            if (!NetworkManager.Singleton.IsServer) return;
            if (PlayerPrefab == null)
            {
                Debug.LogError($"[{nameof(KawaiiNetworkManager)}] PlayerPrefab is null! Cannot spawn player.");
                return;
            }

            // Determine spawn position (could use a SpawnPoint system)
            Vector3 spawnPos = GetSpawnPosition(clientId);

            // Instantiate and spawn over the network
            GameObject playerInstance = Instantiate(PlayerPrefab, spawnPos, Quaternion.identity);
            NetworkObject netObj = playerInstance.GetComponent<NetworkObject>();

            if (netObj == null)
            {
                Debug.LogError($"[{nameof(KawaiiNetworkManager)}] PlayerPrefab missing NetworkObject!");
                Destroy(playerInstance);
                return;
            }

            netObj.SpawnAsPlayerObject(clientId, destroyWithScene: false);

            // Initialise display name from authentication
            var networkedPlayer = playerInstance.GetComponent<NetworkedPlayer>();
            if (networkedPlayer != null)
            {
                string displayName = GetDisplayNameForClient(clientId);
                networkedPlayer.SetDisplayName(displayName);
            }

            Debug.Log($"[{nameof(KawaiiNetworkManager)}] Spawned player object for client {clientId} at {spawnPos}.");
        }

        /// <summary>
        /// Despawns and destroys a player's avatar. Server only.
        /// </summary>
        private void DespawnPlayer(ulong clientId)
        {
            if (!NetworkManager.Singleton.IsServer) return;

            if (NetworkManager.Singleton.ConnectedClients.TryGetValue(clientId, out var client))
            {
                if (client.PlayerObject != null)
                {
                    client.PlayerObject.Despawn(true);
                    Debug.Log($"[{nameof(KawaiiNetworkManager)}] Despawned player object for client {clientId}.");
                }
            }

            // Clean up registry
            var entry = _connectedPlayers.FirstOrDefault(kvp => kvp.Value.OwnerClientId == clientId);
            if (entry.Value != null)
                UnregisterPlayer(entry.Key);
        }

        /// <summary>
        /// Determines a spawn position for <paramref name="clientId"/>.
        /// Uses spawn points if available, otherwise randomises around origin.
        /// </summary>
        private Vector3 GetSpawnPosition(ulong clientId)
        {
            // Look for spawn points in the scene
            var spawnPoints = FindObjectsByType<PlayerSpawnPoint>(FindObjectsSortMode.None);
            if (spawnPoints.Length > 0)
            {
                int idx = (int)(clientId % (ulong)spawnPoints.Length);
                return spawnPoints[idx].transform.position;
            }

            // Fallback: random circle around origin
            float angle = UnityEngine.Random.Range(0f, Mathf.PI * 2f);
            float radius = UnityEngine.Random.Range(1f, 3f);
            return new Vector3(Mathf.Cos(angle) * radius, 0f, Mathf.Sin(angle) * radius);
        }

        /// <summary>
        /// Retrieves a human-readable display name for <paramref name="clientId"/>.
        /// Falls back to "Player #N" if no name source is available.
        /// </summary>
        private string GetDisplayNameForClient(ulong clientId)
        {
            // Try authentication profile name
            if (AuthenticationService.Instance.IsSignedIn)
            {
                string profileName = AuthenticationService.Instance.PlayerName;
                if (!string.IsNullOrWhiteSpace(profileName))
                    return profileName;
            }

            // Fallback
            return $"Player {clientId}";
        }

        // ================================================================
        // Utility
        // ================================================================

        /// <summary>
        /// Ensures Unity Services (Authentication + Relay) are initialised.
        /// Safe to call multiple times — short-circuits if already done.
        /// </summary>
        private async Task EnsureServicesInitializedAsync()
        {
            if (_isInitializingRelay) return;
            _isInitializingRelay = true;

            try
            {
                if (UnityServices.State == ServicesInitializationState.Uninitialized)
                {
                    await UnityServices.InitializeAsync();
                    Debug.Log($"[{nameof(KawaiiNetworkManager)}] Unity Services initialised.");
                }

                if (!AuthenticationService.Instance.IsSignedIn)
                {
                    await AuthenticationService.Instance.SignInAnonymouslyAsync();
                    Debug.Log($"[{nameof(KawaiiNetworkManager)}] Signed in anonymously. Player ID: {AuthenticationService.Instance.PlayerId}");
                }

                IsRelayReady = true;
            }
            catch (Exception ex)
            {
                Debug.LogError($"[{nameof(KawaiiNetworkManager)}] Services init failed: {ex.Message}");
                IsRelayReady = false;
            }
            finally
            {
                _isInitializingRelay = false;
            }
        }

        /// <summary>
        /// Parses a direct connection string in "ip:port" format.
        /// </summary>
        private void ParseDirectConnection(string connectionString)
        {
            string[] parts = connectionString.Split(':');
            string ip = parts[0];
            ushort port = parts.Length > 1 && ushort.TryParse(parts[1], out ushort p)
                ? p
                : (ushort)NetworkConstants.DEFAULT_PORT;

            Transport.SetConnectionData(ip, port);
        }

        /// <summary>
        /// Copies the current join code to the system clipboard.
        /// </summary>
        public void CopyJoinCodeToClipboard()
        {
            if (!string.IsNullOrEmpty(_currentJoinCode))
            {
                GUIUtility.systemCopyBuffer = _currentJoinCode;
                Debug.Log($"[{nameof(KawaiiNetworkManager)}] Join code copied to clipboard: {_currentJoinCode}");
            }
        }

        // ================================================================
        // Events
        // ================================================================

        /// <summary>
        /// Fired on the server when any player connects (including the host).
        /// </summary>
        public event Action<ulong> OnPlayerConnected;

        /// <summary>
        /// Fired on the server and all clients when any player disconnects.
        /// </summary>
        public event Action<ulong> OnPlayerDisconnected;

        /// <summary>
        /// Fired locally when the host has successfully started listening.
        /// </summary>
        public event Action OnHostStarted;

        /// <summary>
        /// Fired locally when this client has successfully connected to a host.
        /// </summary>
        public event Action OnClientConnectedToHost;

        /// <summary>
        /// Fired locally after a disconnect (voluntary or involuntary).
        /// </summary>
        public event Action OnDisconnected;
    }

    // ================================================================
    // Minimal spawn-point marker
    // ================================================================

    /// <summary>
    /// Marker component for player spawn locations. Place in scenes
    /// where players should appear.
    /// </summary>
    public class PlayerSpawnPoint : MonoBehaviour
    {
        [Tooltip("Priority order when multiple spawn points exist. Lower = preferred.")]
        public int Priority = 0;

        [Tooltip("If true, this spawn point is only used for the host player.")]
        public bool HostOnly = false;
    }
}
