using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using UnityEngine;

namespace KawaiiCoolIsland.Chat
{
    /// <summary>
    /// Represents a single chat message with metadata, reactions, and formatting capabilities.
    /// Used across all chat channels in the KawaiiCool Island chat system.
    /// </summary>
    [System.Serializable]
    public class ChatMessage
    {
        #region Message Properties
        /// <summary>
        /// Unique identifier for this message (GUID-based).
        /// </summary>
        public string MessageId;

        /// <summary>
        /// Unique identifier of the sender player.
        /// </summary>
        public string SenderId;

        /// <summary>
        /// Display name of the sender player.
        /// </summary>
        public string SenderName;

        /// <summary>
        /// The message content text (may contain rich text tags for formatting).
        /// </summary>
        public string Content;

        /// <summary>
        /// The chat channel this message was sent in.
        /// </summary>
        public ChatChannel Channel;

        /// <summary>
        /// Unix timestamp (seconds since epoch) when the message was sent.
        /// </summary>
        public long Timestamp;

        /// <summary>
        /// True if this message was generated by the system rather than a player.
        /// </summary>
        public bool IsSystemMessage;

        /// <summary>
        /// The type of message (text, emote, sticker, system, etc.).
        /// </summary>
        public MessageType Type;

        /// <summary>
        /// List of emote reactions attached to this message.
        /// </summary>
        public List<EmoteReaction> Reactions;

        /// <summary>
        /// For whisper messages: the target player's ID.
        /// </summary>
        public string TargetPlayerId;
        #endregion

        #region Computed Properties
        /// <summary>
        /// Returns the message content with rich text tags stripped for plain text display.
        /// </summary>
        public string PlainContent => StripRichTextTags(Content);

        /// <summary>
        /// Returns the age of this message in seconds.
        /// </summary>
        public double AgeSeconds => DateTimeOffset.UtcNow.ToUnixTimeSeconds() - Timestamp;

        /// <summary>
        /// Returns a formatted relative time string (e.g., "2m ago").
        /// </summary>
        public string RelativeTime
        {
            get
            {
                double age = AgeSeconds;
                if (age < 60) return "just now";
                if (age < 3600) return $"{(int)(age / 60)}m ago";
                if (age < 86400) return $"{(int)(age / 3600)}h ago";
                return $"{(int)(age / 86400)}d ago";
            }
        }

        /// <summary>
        /// Returns the total count of all reactions on this message.
        /// </summary>
        public int TotalReactionCount => Reactions?.Sum(r => r.Count) ?? 0;
        #endregion

        #region Public Methods
        /// <summary>
        /// Returns the formatted timestamp as a readable time string (HH:mm).
        /// </summary>
        /// <returns>Formatted time string in HH:mm format.</returns>
        public string GetFormattedTime()
        {
            var dateTime = DateTimeOffset.FromUnixTimeSeconds(Timestamp).LocalDateTime;
            return dateTime.ToString("HH:mm");
        }

        /// <summary>
        /// Returns the formatted timestamp with date (HH:mm:ss dd/MM/yyyy).
        /// </summary>
        /// <returns>Full formatted date and time string.</returns>
        public string GetFormattedDateTime()
        {
            var dateTime = DateTimeOffset.FromUnixTimeSeconds(Timestamp).LocalDateTime;
            return dateTime.ToString("HH:mm:ss dd/MM/yyyy");
        }

        /// <summary>
        /// Returns the message content wrapped with colored sender name prefix.
        /// </summary>
        /// <param name="playerNameColor">Color for the sender name.</param>
        /// <returns>Formatted message string with colored name prefix.</returns>
        public string GetColoredContent(Color playerNameColor)
        {
            string hexColor = ColorToHex(playerNameColor);
            string channelPrefix = GetChannelPrefix();
            string namePrefix = IsSystemMessage
                ? $"<color={hexColor}>[System]</color>"
                : $"<color={hexColor}>{SenderName}</color>";

            return $"{channelPrefix}{namePrefix}: {Content}";
        }

        /// <summary>
        /// Returns the message formatted for display in a specific channel's chat log.
        /// Includes timestamp, channel color, and sender name.
        /// </summary>
        /// <param name="channelColor">The color associated with the channel.</param>
        /// <param name="showTimestamp">Whether to include the timestamp.</param>
        /// <returns>Fully formatted message string.</returns>
        public string GetFormattedMessage(Color channelColor, bool showTimestamp = true)
        {
            var sb = new System.Text.StringBuilder();

            if (showTimestamp)
            {
                sb.Append($"<color=#888888>[{GetFormattedTime()}]</color> ");
            }

            if (Channel == ChatChannel.Whisper)
            {
                sb.Append("<color=#FF80FF>[Whisper]</color> ");
            }
            else if (Channel != ChatChannel.World)
            {
                string channelHex = ColorToHex(channelColor);
                sb.Append($"<color={channelHex}>[{Channel}]</color> ");
            }

            if (IsSystemMessage)
            {
                sb.Append($"<color=yellow>{Content}</color>");
            }
            else
            {
                sb.Append($"<b>{SenderName}</b>: {Content}");
            }

            return sb.ToString();
        }

        /// <summary>
        /// Adds an emote reaction to this message.
        /// </summary>
        /// <param name="emoteId">The emote identifier.</param>
        /// <param name="reactorId">The player adding the reaction.</param>
        public void AddReaction(string emoteId, string reactorId)
        {
            if (Reactions == null)
            {
                Reactions = new List<EmoteReaction>();
            }

            // Check if this player already reacted with this emote - if so, remove it (toggle behavior)
            var existingReaction = Reactions.Find(r => r.EmoteId == emoteId);
            if (existingReaction != null)
            {
                if (existingReaction.ReactorIds.Contains(reactorId))
                {
                    // Player already reacted with this emote, so remove their reaction
                    RemoveReaction(emoteId, reactorId);
                    return;
                }
                existingReaction.ReactorIds.Add(reactorId);
            }
            else
            {
                Reactions.Add(new EmoteReaction
                {
                    EmoteId = emoteId,
                    EmoteSpritePath = $"Emotes/{emoteId}",
                    ReactorIds = new List<string> { reactorId }
                });
            }
        }

        /// <summary>
        /// Removes an emote reaction from this message.
        /// </summary>
        /// <param name="emoteId">The emote identifier to remove.</param>
        /// <param name="reactorId">The player removing the reaction.</param>
        public void RemoveReaction(string emoteId, string reactorId)
        {
            if (Reactions == null) return;

            var reaction = Reactions.Find(r => r.EmoteId == emoteId);
            if (reaction == null) return;

            reaction.ReactorIds.Remove(reactorId);

            // Remove the reaction entirely if no reactors remain
            if (reaction.ReactorIds.Count == 0)
            {
                Reactions.Remove(reaction);
            }
        }

        /// <summary>
        /// Checks if a specific player has reacted with a specific emote.
        /// </summary>
        /// <param name="emoteId">The emote to check.</param>
        /// <param name="reactorId">The player to check.</param>
        /// <returns>True if the player has reacted with the emote.</returns>
        public bool HasPlayerReacted(string emoteId, string reactorId)
        {
            if (Reactions == null) return false;

            var reaction = Reactions.Find(r => r.EmoteId == emoteId);
            return reaction?.ReactorIds.Contains(reactorId) ?? false;
        }

        /// <summary>
        /// Returns the count of a specific emote reaction.
        /// </summary>
        /// <param name="emoteId">The emote to count.</param>
        /// <returns>Number of players who reacted with this emote.</returns>
        public int GetReactionCount(string emoteId)
        {
            if (Reactions == null) return 0;

            var reaction = Reactions.Find(r => r.EmoteId == emoteId);
            return reaction?.Count ?? 0;
        }

        /// <summary>
        /// Creates a deep copy of this message with a new MessageId.
        /// </summary>
        /// <returns>A new ChatMessage instance with copied values.</returns>
        public ChatMessage Clone()
        {
            return new ChatMessage
            {
                MessageId = Guid.NewGuid().ToString("N").Substring(0, 16),
                SenderId = SenderId,
                SenderName = SenderName,
                Content = Content,
                Channel = Channel,
                Timestamp = Timestamp,
                IsSystemMessage = IsSystemMessage,
                Type = Type,
                Reactions = Reactions?.Select(r => new EmoteReaction
                {
                    EmoteId = r.EmoteId,
                    EmoteSpritePath = r.EmoteSpritePath,
                    ReactorIds = new List<string>(r.ReactorIds)
                }).ToList(),
                TargetPlayerId = TargetPlayerId
            };
        }

        /// <summary>
        /// Returns a summary string for debugging purposes.
        /// </summary>
        /// <returns>Debug string with key message info.</returns>
        public override string ToString()
        {
            return $"[{GetFormattedTime()}] [{Channel}] {SenderName}: {PlainContent} " +
                   $"(Reactions: {TotalReactionCount})";
        }
        #endregion

        #region Private Helpers
        /// <summary>
        /// Converts a Unity Color to a hex string for rich text formatting.
        /// </summary>
        private static string ColorToHex(Color color)
        {
            int r = Mathf.RoundToInt(color.r * 255);
            int g = Mathf.RoundToInt(color.g * 255);
            int b = Mathf.RoundToInt(color.b * 255);
            return $"#{r:X2}{g:X2}{b:X2}";
        }

        /// <summary>
        /// Returns the channel prefix string for this message.
        /// </summary>
        private string GetChannelPrefix()
        {
            switch (Channel)
            {
                case ChatChannel.Whisper:
                    return "<color=#FF80FF>[W]</color> ";
                case ChatChannel.Party:
                    return "<color=#CC66FF>[P]</color> ";
                case ChatChannel.Island:
                    return "<color=#FF9933>[I]</color> ";
                case ChatChannel.Proximity:
                    return "<color=#80FF80>[N]</color> ";
                case ChatChannel.System:
                    return "<color=yellow>[S]</color> ";
                default:
                    return "";
            }
        }

        /// <summary>
        /// Strips Unity rich text tags from the input string.
        /// </summary>
        private static string StripRichTextTags(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;
            return Regex.Replace(input, "<[^>]+>", string.Empty);
        }
        #endregion
    }

    /// <summary>
    /// Enumeration of different message types supported by the chat system.
    /// </summary>
    public enum MessageType
    {
        /// <summary>Standard text message.</summary>
        Text,
        /// <summary>Emote action message (e.g., *dances*).</summary>
        Emote,
        /// <summary>Sticker/image message.</summary>
        Sticker,
        /// <summary>System-generated message.</summary>
        System,
        /// <summary>Trade-related message.</summary>
        Trade,
        /// <summary>Party invitation message.</summary>
        PartyInvite
    }

    /// <summary>
    /// Represents an emote reaction on a chat message.
    /// Tracks which players have reacted with this emote.
    /// </summary>
    [System.Serializable]
    public class EmoteReaction
    {
        /// <summary>
        /// Unique identifier for the emote (e.g., "heart", "laugh", "thumbs_up").
        /// </summary>
        public string EmoteId;

        /// <summary>
        /// Resource path to the emote sprite for UI display.
        /// </summary>
        public string EmoteSpritePath;

        /// <summary>
        /// List of player IDs who have reacted with this emote.
        /// </summary>
        public List<string> ReactorIds = new();

        /// <summary>
        /// Number of players who have reacted with this emote.
        /// </summary>
        public int Count => ReactorIds?.Count ?? 0;

        /// <summary>
        /// Checks if a specific player has reacted with this emote.
        /// </summary>
        /// <param name="reactorId">The player ID to check.</param>
        /// <returns>True if the player has reacted.</returns>
        public bool HasReacted(string reactorId)
        {
            return ReactorIds != null && ReactorIds.Contains(reactorId);
        }

        /// <summary>
        /// Returns a debug string representation.
        /// </summary>
        public override string ToString()
        {
            return $"{EmoteId} x{Count}";
        }
    }
}
